name: K6 with Github Actions
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: k6.js
          flags: --vus 1 --duration 10s